### ISSUE TITLE
Create Gatsby starter?

### ISSUE THREAD

**Issue by KyleAMathews** [wpioneer/blog#1]
I <3 your site design. If it's something you wouldn't mind sharing, it'd make an awesome Gatsby starter. Lots of people that will be creating Gatsby sites will be using it for creating personal sites/blogs and I think a lot of people would love your design.

Just a thought :)

**Comment by wpioneer** [comment]
Thank you ;)

I think such a structure like here is perfect for Gatsby Starter.

**Comment by KyleAMathews** [comment]
Great! When you have it ready, just create a PR to Gatsby with a link in the README to your starter. It'll be awesome to start building up a larger and larger collection of starters.
